name: Build and deploy Python project to Azure Function App - formula-checker-func

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.10'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target="./.python_packages/lib/site-packages"

      - name: Archive function app
        run: |
          cd formula_checker_v2
          zip -r ../functionapp.zip . -x "*.git*" -x "*__pycache__*"

      - name: List contents of zip file
        run: unzip -l functionapp.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E9A0888334AC4B3E96792F74392AF421 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EAEEE056E8394BDBB4FF6CAE9E446FAD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DA5032AFABC34CC29EF26F69DA1CF475 }}

      - name: Deploy to Azure Function App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'formula-checker-func'
          package: functionapp.zip